title = "Sveriges Synskadades Schackförbund"
baseURL = "https://srfschack.org"
languageCode = "sv"
theme = ["ananke"]

DefaultContentLanguage = "sv"
SectionPagesMenu = "main"
Paginate = 5
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
 changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "img/sssf.png"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 5
  mainSections = ["post"]

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/groups/622091821139404/"
